services:
  mockehr:
    restart: on-failure
    build:
      context: ./interop-mock-ehr
      dockerfile: Dockerfile
    image: interop-mock-ehr:local
    environment:
      - MOCK_EHR_DB_HOST=mockehrmysql
      - MOCK_EHR_DB_PORT=33060
      - MOCK_EHR_DB_NAME=mock_ehr_db
      - MOCK_EHR_DB_USER=springuser
      - MOCK_EHR_DB_PASS=ThePassword
    ports:
      - "8080:8080"
    depends_on:
      - mockehrmysql

  mockehrmysql:
    restart: always
    image: mysql/mysql-server:latest-aarch64
    environment:
      - MYSQL_DATABASE=mock_ehr_db
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=springuser
      - MYSQL_PASSWORD=ThePassword
    ports:
      - "33060:33060"
