services:
  mockehr:
    restart: on-failure
    build:
      context: ./interop-mock-ehr
      dockerfile: Dockerfile
    image: interop-mock-ehr:local
    environment:
      - MOCK_EHR_DB_HOST=mockehrmysql
      - MOCK_EHR_DB_PORT=33060
      - MOCK_EHR_DB_NAME=mock_ehr_db
      - MOCK_EHR_DB_USER=springuser
      - MOCK_EHR_DB_PASS=ThePassword
    ports:
      - "8081:8080"
    depends_on:
      mockehrmysql:
        condition: service_healthy

  mockehrinit:
    restart: "no"
    build:
      context: ./init
      dockerfile: Dockerfile
    image: interop-mock-ehr-init:local
    depends_on:
      mockehrmysql:
        condition: service_healthy

  mockehrmysql:
    restart: always
    image: mysql/mysql-server:latest
    environment:
      - MYSQL_DATABASE=mock_ehr_db
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=springuser
      - MYSQL_PASSWORD=ThePassword
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "springuser", "-pThePassword" ]
      timeout: 5s
      retries: 3
