version: "2"

services:
  mysql:
    restart: always
    image: mysql:latest
    container_name: my-sql-latest
    environment:
      - MYSQL_DATABASE=mock-ehr-mysql
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 33080:3306
