[libraries]
hapi-fhir-base = "ca.uhn.hapi.fhir:hapi-fhir-base:6.0.1"
hapi-fhir-server = "ca.uhn.hapi.fhir:hapi-fhir-server:6.0.1"
hapi-fhir-server-openapi = "ca.uhn.hapi.fhir:hapi-fhir-server-openapi:6.0.1"
hapi-fhir-structures-r4 = "ca.uhn.hapi.fhir:hapi-fhir-structures-r4:6.0.1"
interop-ehr-epic = "com.projectronin.interop.ehr:interop-ehr-epic:1.1.0"
interop-fhir = "com.projectronin.interop.fhir:interop-fhir:1.0.0"
ktor-client-cio = "io.ktor:ktor-client-cio:2.0.2"
ktor-client-core = "io.ktor:ktor-client-core:2.0.2"
mockk = "io.mockk:mockk:1.12.4"
mysql-connector-java = "mysql:mysql-connector-java:8.0.29"
protobuf-java = "com.google.protobuf:protobuf-java:3.20.1"
spring-boot-parent = "org.springframework.boot:spring-boot-parent:2.7.0"
springdoc-openapi-data = "org.springdoc:springdoc-openapi-data-rest:1.6.9"
springdoc-openapi-kotlin = "org.springdoc:springdoc-openapi-kotlin:1.6.9"
springdoc-openapi-ui = "org.springdoc:springdoc-openapi-ui:1.6.9"
testcontainers-bom = "org.testcontainers:testcontainers-bom:1.17.2"
json-patch = "com.github.java-json-tools:json-patch:1.13"

[bundles]
hapi-fhir = ["hapi-fhir-base", "hapi-fhir-server", "hapi-fhir-structures-r4", "hapi-fhir-server-openapi"]
springdoc-openapi = ["springdoc-openapi-data", "springdoc-openapi-kotlin", "springdoc-openapi-ui"]
