[libraries]
hapi-fhir-base = "ca.uhn.hapi.fhir:hapi-fhir-base:6.2.4"
hapi-fhir-server = "ca.uhn.hapi.fhir:hapi-fhir-server:6.2.4"
hapi-fhir-server-openapi = "ca.uhn.hapi.fhir:hapi-fhir-server-openapi:6.2.4"
hapi-fhir-structures-r4 = "ca.uhn.hapi.fhir:hapi-fhir-structures-r4:6.2.4"
hapi-fhir-structures-stu3 = "ca.uhn.hapi.fhir:hapi-fhir-structures-dstu3:6.2.4"
hapi-hl7v2-base = "ca.uhn.hapi:hapi-base:2.3"
hapi-hl7v2-http = "ca.uhn.hapi:hapi-hl7overhttp:2.3"
hapi-hl7v2-251 = "ca.uhn.hapi:hapi-structures-v251:2.3"
interop-ehr-cerner = "com.projectronin.interop.ehr:interop-ehr-cerner:7.0.0"
interop-ehr-epic = "com.projectronin.interop.ehr:interop-ehr-epic:7.0.0"
interop-fhir = "com.projectronin.interop.fhir:interop-fhir:5.0.0"
ktor-client-cio = "io.ktor:ktor-client-cio:2.2.2"
ktor-client-core = "io.ktor:ktor-client-core:2.2.2"
mockk = "io.mockk:mockk:1.13.3"
mysql-connector-java = "com.mysql:mysql-connector-j:8.0.31"
protobuf-java = "com.google.protobuf:protobuf-java:3.21.12"
spring-boot-parent = "org.springframework.boot:spring-boot-parent:2.7.5"
springdoc-openapi-data = "org.springdoc:springdoc-openapi-data-rest:1.6.14"
springdoc-openapi-kotlin = "org.springdoc:springdoc-openapi-kotlin:1.6.14"
springdoc-openapi-ui = "org.springdoc:springdoc-openapi-ui:1.6.14"
testcontainers-bom = "org.testcontainers:testcontainers-bom:1.17.6"
json-patch = "com.github.java-json-tools:json-patch:1.13"

[bundles]
hapi-fhir = ["hapi-fhir-base", "hapi-fhir-server", "hapi-fhir-structures-r4", "hapi-fhir-server-openapi", "hapi-fhir-structures-stu3"]
hapi-hl7v2 = ["hapi-hl7v2-base", "hapi-hl7v2-251", "hapi-hl7v2-http"]
springdoc-openapi = ["springdoc-openapi-data", "springdoc-openapi-kotlin", "springdoc-openapi-ui"]
