name: Build and Deploy Docker Image to DEV

on:
  workflow_run:
    workflows: [ Tests ]
    types: [ completed ]
    branches: [ main ]

jobs:
  main-image-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Push multiplatform Docker:latest to Nexus
    uses: projectronin/github/.github/workflows/image_push_nexus.yml@image_push_nexus/v2
    with:
      base-directory: ./interop-mock-ehr
      image-tag: latest,${{ github.sha }}
      repo: "interop-mock-ehr"
      build_boot_jar: true
    secrets:
      username: ${{ secrets.NEXUS_DOCKER_USERNAME }}
      password: ${{ secrets.NEXUS_DOCKER_PASSWORD }}

  init-image-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Push multiplatform Docker:init to Nexus
    uses: projectronin/github/.github/workflows/image_push_nexus.yml@image_push_nexus/v2
    with:
      base-directory: ./init
      image-tag: latest,${{ github.sha }}
      repo: "interop-mock-ehr-init"
      build_boot_jar: false
    secrets:
      username: ${{ secrets.NEXUS_DOCKER_USERNAME }}
      password: ${{ secrets.NEXUS_DOCKER_PASSWORD }}

  deploy-argocd-dev:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    needs: [ main-image-push ]
    name: Deploy Images to DEV
    uses: projectronin/github/.github/workflows/argocd_deploy.yml@argocd_deploy/v1
    with:
      environment: dev
      image-tag: ${{ github.sha }}
    secrets:
      argocd-svc-automation: ${{ secrets.ARGOCD_SVC_AUTOMATION }}

